version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: contentdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    volumes:
      - ./blog_content.csv:/docker-entrypoint-initdb.d/blog_content.csv
      - ./contentdb.sql:/docker-entrypoint-initdb.d/contentdb.sql
  web:
    image: php:7.2.2-apache
    build: ./php/
    depends_on:
      - db
    volumes:
      - ./blog/:/var/www/html/

    ports:
      - "80:80"
