version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 348jhb
      MYSQL_DATABASE: contentdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      LANG: C.UTF_8
    ports:
      - "9906:3306"
    volumes:
      - ./news_content.csv:/docker-entrypoint-initdb.d/news_content.csv
      - ./contentdb.sql:/docker-entrypoint-initdb.d/contentdb.sql

    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  
  web:
    image: php:7.2.2-apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./news/:/var/www/html/
    ports:
      - "80:80"
     
